vae_model_params:
  name: 'VQVAE'
  in_channels: 3
  embedding_dim: 64
  num_embeddings: 512
  img_size: 64
  beta: 0.25
  ckpt_path: "D:\\MyCode\\GenerativeAI\\vae\\logs\\VQVAE\\version_3\\checkpoints\\last.ckpt"

ar_model_params:
  name: 'PixelCNN'
  n_classes: 40

data_params:
  data_dir: "D:\\MyCode\\GenerativeAI\\data"
  train_batch_size: 64
  val_batch_size:  64
  patch_size: 64
  num_workers: 4

exp_params:
  LR: 0.001
  weight_decay: 0.0
  scheduler_gamma: 0.0
  kld_weight: 0.00025
  manual_seed: 1265
  skip_sampling: True

trainer_params:
  max_epochs: 10
  accelerator: 'gpu'
  devices: 1

logging_params:
  save_dir: "logs/"
  name: 'VQVAE'